#cloud-config # Comment
users: # Keyword to configure a user
  - name: ubuntu # Name of the user
    sudo: ALL=(ALL) NOPASSWD:ALL # gives the user right to use sudo commands without inputing the password
    groups: users, admin # assigned the user to the listed groups
    home: /home/ubuntu # Assignes the listed folder as the homeo folder of the user
    shell: /bin/bash # asignes the listed shell as the shell of the user
    ssh_authorized_keys: # SSH-Key with which you can log into the user
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC0WGP1EZykEtv5YGC9nMiPFW3U3DmZNzKFO5nEu6uozEHh4jLZzPNHSrfFTuQ2GnRDSt+XbOtTLdcj26+iPNiFoFha42aCIzYjt6V8Z+SQ9pzF4jPPzxwXfDdkEWylgoNnZ+4MG1lNFqa8aO7F62tX0Yj5khjC0Bs7Mb2cHLx1XZaxJV6qSaulDuBbLYe8QUZXkMc7wmob3PM0kflfolR3LE7LResIHWa4j4FL6r5cQmFlDU2BDPpKMFMGUfRSFiUtaWBNXFOWHQBC2+uKmuMPYP4vJC9sBgqMvPN/X2KyemqdMvdKXnCfrzadHuSSJYEzD64Cve5Zl9yVvY4AqyBD aws-key       
ssh_pwauth: false # Deaklivates SSH-password-login
disable_root: false # Forbids the user to take away the root acces
package_update: true # Allows the user to install packages
packages: # installs the packages listed below
  - curl 
  - wget 
