#cloud-config
users: # Keyword to configure a user
  - name: ubuntu # Name of the user
    sudo: ALL=(ALL) NOPASSWD:ALL # gives the user right to use sudo commands without inputing the password
    groups: users, admin # assigned the user to the listed groups
    home: /home/ubuntu # Assignes the listed folder as the homeo folder of the user
    shell: /bin/bash # asignes the listed shell as the shell of the user
    ssh_authorized_keys: # SSH-Key with which you can log into the user
        # my private key
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCCr5+BBKVeaBmBW3XdvW3uikOxkyWvLlmY/W9QwK7Pa/ALlBRw4W2rfyOa+BxuKSZsVwLKaQKfc0dpKve22HPquuSAC7vfARSopZCXyTcusyNw/HoUuSnZD9gRl7zaVOOZ+WpM0dlUP4upawPMHgeNRyXFRDTzi+Z5B/XAc8YXGxyEKxQvz6dEJ+vBa6pLz5ZR+tH4hbymHpzr5y3n6S9zsOcj0O7+YbJeanUNRZd6xENTWc9v9/dOA+NKHTgyUcIYH1Dc03WfswMkrwqEZLjWbKBbKntrAbwqLhmjlPEYboiuXLvFWIGIvNOcXQGSrhHsr/n2QmP7A01hRZifnABv aws-key       
        # teacher's private key
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC0WGP1EZykEtv5YGC9nMiPFW3U3DmZNzKFO5nEu6uozEHh4jLZzPNHSrfFTuQ2GnRDSt+XbOtTLdcj26+iPNiFoFha42aCIzYjt6V8Z+SQ9pzF4jPPzxwXfDdkEWylgoNnZ+4MG1lNFqa8aO7F62tX0Yj5khjC0Bs7Mb2cHLx1XZaxJV6qSaulDuBbLYe8QUZXkMc7wmob3PM0kflfolR3LE7LResIHWa4j4FL6r5cQmFlDU2BDPpKMFMGUfRSFiUtaWBNXFOWHQBC2+uKmuMPYP4vJC9sBgqMvPN/X2KyemqdMvdKXnCfrzadHuSSJYEzD64Cve5Zl9yVvY4AqyBD aws-key
ssh_pwauth: false 
disable_root: false 
package_update: true 
packages: # installing extra packages
  - curl 
  - wget 
  - apache2
  - php
  - libapache2-mod-php
write_files:
    - path: /var/www/html/image.php
      permissions: "0644"
      content: |
        <?php
          $ihrname = 'pishchan"

          <html>
            <head>
              <title>echo($ihrname)</title>
            </head>
          <body>
            This is a cool picture of an average everyday crow. I love crows.
            <br/>
            <img width=300 src="https://s3.amazonaws.com/yan-bucket-v1.0/crow-image.jpg"/>
            I have takes this image from unsplash.com
          </body>
        </html>
        ?>
runcmd:
  - sudo a2enconf adminer
  - sudo systemctl restart mariadb.service
  - sudo systemctl restart apache2

